Implement version option
YukieK/GeekHours pull request #21
Opened 2019-06-08 05:05 UTC by YukieK

Implement `geekhours --version` command.
This PR closes #7.

2019-06-08 05:33 UTC, mitsutaka commented
Can you let make setup installs wheel package?
```
 setup:
-       pip3 install -U pylint pytest pycodestyle yapf --user
+       pip3 install -U pylint pytest pycodestyle yapf wheel --user
```

2019-06-08 05:41 UTC, mitsutaka commented
Fix this error when no argument specified.
```
$ geekhours
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/geekhours", line 316, in <module>
    main()
  File "/home/ubuntu/.local/bin/geekhours", line 307, in main
    args = get_args(today)
  File "/home/ubuntu/.local/bin/geekhours", line 300, in get_args
    args = parser.parse_args()
  File "/usr/lib/python3.6/argparse.py", line 1743, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1775, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 2010, in _parse_known_args
    ', '.join(required_actions))
TypeError: sequence item 0: expected str instance, NoneType found
```

2019-06-08 05:43 UTC, mitsutaka requested changes
LGTM. but pls fix what I commented above.

2019-06-17 01:39 UTC, YukieK commented
Reflected the comments.

2019-06-17 03:30 UTC, mitsutaka commented on bin/geekhours
> +    """ Parsers for 'corse', 'done' and 'sum' sub-commands """
s/corse/course/

2019-06-17 05:20 UTC, YukieK commented on bin/geekhours
> +    """ Parsers for 'corse', 'done' and 'sum' sub-commands """
Fixed.

2019-06-17 07:06 UTC, mitsutaka approved these changes
LGTM

2019-06-17 07:07 UTC, merged